version: "3.1"

services:
  db:
    image: postgres:12.4
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ~/docker/postgres-employee:/var/lib/postgresql/data
